// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDFEwuiNdf0_QeW_ITT2ajvGvKpS8cE9s',
    appId: '1:752703554088:web:83b35f22f6ca4e0a1feb1d',
    messagingSenderId: '752703554088',
    projectId: 'moviestream-167bb',
    authDomain: 'moviestream-167bb.firebaseapp.com',
    storageBucket: 'moviestream-167bb.firebasestorage.app',
    measurementId: 'G-YVVJFHQNPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCtAHpxr1BmV7ohBUahiG3jCgbQcRQ_nI',
    appId: '1:752703554088:android:43e807027c9bf10e1feb1d',
    messagingSenderId: '752703554088',
    projectId: 'moviestream-167bb',
    storageBucket: 'moviestream-167bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnrSobwpAUS3AkEjb3MNgrBrvR2v6ZnpA',
    appId: '1:752703554088:ios:5cfc0a5a21dfd60b1feb1d',
    messagingSenderId: '752703554088',
    projectId: 'moviestream-167bb',
    storageBucket: 'moviestream-167bb.firebasestorage.app',
    iosBundleId: 'com.example.filmelist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnrSobwpAUS3AkEjb3MNgrBrvR2v6ZnpA',
    appId: '1:752703554088:ios:5cfc0a5a21dfd60b1feb1d',
    messagingSenderId: '752703554088',
    projectId: 'moviestream-167bb',
    storageBucket: 'moviestream-167bb.firebasestorage.app',
    iosBundleId: 'com.example.filmelist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDFEwuiNdf0_QeW_ITT2ajvGvKpS8cE9s',
    appId: '1:752703554088:web:c8ce61d24975a1541feb1d',
    messagingSenderId: '752703554088',
    projectId: 'moviestream-167bb',
    authDomain: 'moviestream-167bb.firebaseapp.com',
    storageBucket: 'moviestream-167bb.firebasestorage.app',
    measurementId: 'G-SP8YFD9TQ7',
  );
}
